interledger4j/ilpv4-connector

ilpv4-connector-it/pom.xml, ilpv4-connector-it/src/main/java/org/interledger/ilpv4/connector/it/Architectures.java, ilpv4-connector-it/src/main/java/org/interledger/ilpv4/connector/it/graph/Edge.java, ilpv4-connector-it/src/main/java/org/interledger/ilpv4/connector/it/graph/Graph.java, ilpv4-connector-it/src/main/java/org/interledger/ilpv4/connector/it/graph/RemoteVertex.java, ilpv4-connector-it/src/main/java/org/interledger/ilpv4/connector/it/graph/ServerVertex.java, ilpv4-connector-it/src/main/java/org/interledger/ilpv4/connector/it/graph/Vertex.java, ilpv4-connector-it/src/main/java/org/interledger/ilpv4/connector/it/graph/edges/PeeringEdge.java, ilpv4-connector-it/src/test/java/org/interledger/ilpv4/connector/it/ArchitecturesTest.java, ilpv4-connector-server/src/main/java/org/interledger/ilpv4/connector/ConnectorServer.java, ilpv4-connector-server/src/main/java/org/interledger/ilpv4/connector/ConnectorServerMain.java, ilpv4-connector-server/src/main/java/org/interledger/ilpv4/connector/config/ConnectorServerConfig.java, ilpv4-connector-server/src/main/java/org/interledger/ilpv4/connector/support/ConnectorServerSettings.java, ilpv4-connector-server/src/main/java/org/interledger/ilpv4/connector/support/Server.java, pom.xml
Add the ability to start multiple ConnectorServer's in a graph configuration.
=> Initial implementation of graph system

.circleci/config.yml
=> Add support for CircleCI

pom.xml
=> Add Code Coverage

ilpv4-connector-crypto/connector-crypto-cli/pom.xml, ilpv4-connector-link/src/main/java/org/interledger/connector/link/CircuitBreakingLink.java, ilpv4-connector-link/src/test/java/org/interledger/connector/link/CircuitBreakingLinkPredicateTest.java, pom.xml
=> Bump versions

ilpv4-connector-routing-impl/src/main/java/com/sappenin/interledger/ilpv4/connector/routing/ChildAccountPaymentRouter.java, ilpv4-connector-server/src/main/java/com/sappenin/interledger/ilpv4/connector/server/spring/settings/SpringConnectorConfig.java, ilpv4-connector-service-impl/pom.xml, ilpv4-connector-service-impl/src/main/java/com/sappenin/interledger/ilpv4/connector/packetswitch/DefaultILPv4PacketSwitch.java, ilpv4-connector-service-impl/src/main/java/com/sappenin/interledger/ilpv4/connector/packetswitch/filters/DefaultPacketSwitchFilterChain.java, ilpv4-connector-service-impl/src/test/java/com/sappenin/interledger/ilpv4/connector/packetswitch/DefaultILPv4PacketSwitchTest.java, ilpv4-connector-service-impl/src/test/java/com/sappenin/interledger/ilpv4/connector/packetswitch/filters/DefaultPacketSwitchFilterChainTest.java, pom.xml
* Enable cached AccountSettings to improve performance.
* Introduce Caffeine (https://github.com/ben-manes/caffeine), a high-performance Java cache, into the codebase, because it offers much better perf than Guava cache.
=> Fixes #142

.circleci/config.yml, ilpv4-connector-accounts/src/main/java/org/interledger/connector/accounts/AccountBalanceSettings.java, ilpv4-connector-jackson/src/test/java/org/interledger/ilpv4/connector/jackson/model/AccountSettingsTest.java, ilpv4-connector-persistence/src/main/java/org/interledger/ilpv4/connector/persistence/entities/AccountBalanceSettingsEntity.java, ilpv4-connector-persistence/src/main/resources/db/changelogs/base/changelog.xml, ilpv4-connector-persistence/src/test/java/org/interledger/ilpv4/connector/persistence/repositories/AccountSettingsRepositoryTest.java, ilpv4-connector-server/src/main/java/com/sappenin/interledger/ilpv4/connector/server/spring/controllers/converters/AccountBalanceSettingsConverter.java, ilpv4-connector-server/src/main/java/com/sappenin/interledger/ilpv4/connector/server/spring/settings/properties/AccountBalanceSettingsFromPropertyFile.java, ilpv4-connector-server/src/test/java/com/sappenin/interledger/ilpv4/connector/server/spring/controllers/converters/AccountBalanceSettingsConverterTest.java, ilpv4-connector-server/src/test/java/com/sappenin/interledger/ilpv4/connector/server/spring/controllers/converters/AccountSettingsConverterTest.java, ilpv4-connector-server/src/test/java/com/sappenin/interledger/ilpv4/connector/server/spring/settings/ConnectorSettingsFromPropertyFileTest.java, ilpv4-connector-server/src/test/resources/application-connector-unit-test.yml, pom.xml
=> Fixes #247

ilpv4-connector-service-impl/src/main/java/org/interledger/ilpv4/connector/balances/RedisBalanceTracker.java, ilpv4-connector-service-impl/src/test/java/org/interledger/ilpv4/connector/balances/RedisBalanceTrackerRefundOutgoingSettlementTest.java
=> Add documentation for choice of long

ilpv4-connector-persistence/pom.xml
=> Disable prompt for non-local DBs

connector-ilpv4-api/src/main/java/org/interledger/ilpv4/ILPv4MulitSender.java, connector-ilpv4-api/src/main/java/org/interledger/ilpv4/ILPv4Sender.java, connector-it/src/test/java/org/interledger/connector/it/AbstractBlastIT.java, connector-it/src/test/java/org/interledger/connector/it/blast/TwoConnectorBlastPingTestIT.java, connector-link/src/main/java/org/interledger/connector/link/LinkSender.java, connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpReceiver.java, connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpSender.java, connector-server/src/test/java/org/interledger/connector/server/ilphttp/JwtBlastEndpointTest.java, connector-service-api/src/main/java/org/interledger/connector/packetswitch/ILPv4PacketSwitch.java, connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java, connector-service-impl/src/main/java/org/interledger/connector/links/filters/OutgoingBalanceLinkFilter.java, connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/BalanceIlpPacketFilter.java, connector-service-impl/src/test/java/org/interledger/connector/links/ping/PingLoopbackLinkTest.java, connector-service-impl/src/test/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitchTest.java, connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/DefaultPacketSwitchFilterChainTest.java, connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/PeerProtocolPacketFilterTest.java
=> Update for new PacketHandler/Mapper

connector-link-blast/pom.xml, connector-link-blast/src/main/java/org/interledger/connector/link/blast/JwtBlastHttpSender.java, connector-routing-impl/pom.xml, connector-routing-impl/src/main/java/org/interledger/connector/routing/ChildAccountPaymentRouter.java, connector-server/pom.xml, connector-server/src/main/java/org/interledger/connector/server/spring/auth/blast/IlpOverHttpAuthenticationProvider.java, connector-service-impl/src/main/java/org/interledger/connector/javax/money/providers/CryptoCompareRateProvider.java, connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/RateLimitIlpPacketFilter.java, connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/RateLimitIlpPacketFilterTest.java, pom.xml
=> caffeinated connector

connector-link/src/test/java/org/interledger/connector/link/CircuitBreakingLinkTest.java, connector-persistence/pom.xml, pom.xml
=> Fixes dependabot PRs

connector-jackson/src/main/java/org/interledger/connector/jackson/ObjectMapperFactory.java, connector-server/pom.xml, connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/JacksonConfig.java, connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
addresses https://github.com/sappenin/java-ilpv4-connector/issues/102
=> configure Jackson to ignore unknown properties

connector-model/src/main/java/org/interledger/connector/settings/ConnectorSettings.java, connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorSettingsFromPropertyFile.java, connector-server/src/test/java/org/interledger/connector/server/spring/settings/ConnectorSettingsFromPropertyFileTest.java, connector-server/src/test/resources/application-connector-unit-test.yml, connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java, connector-service-impl/src/test/java/org/interledger/connector/links/DefaultNextHopPacketMapperTest.java
add test coverage to DefaultNextHopPacketMapper
refactor DefaultNextHopPacketMapper so that Clock and CurrencyConversion can be provided by test
=> make maxHoldTime and minMessageWindow configurable and improve javadoc

connector-server/src/main/java/org/interledger/connector/server/spring/settings/javamoney/JavaMoneyConfig.java, connector-server/src/test/java/org/interledger/connector/server/javamoney/JavaMoneyConfigTest.java, connector-server/src/test/resources/application-test.yml
=> use okhttp in JavaMoneyConfig (for CryptoCompare)

connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java, connector-service-impl/src/test/java/org/interledger/connector/fx/JavaMoneyUtilsTest.java
Signed-off-by: Ian Simpson <ian.g.simpson@gmail.com>
=> performance notes around fx calculations #223

connector-server/pom.xml, connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/AccountsController.java, connector-server/src/test/java/org/interledger/connector/server/javamoney/AdminApiSecurityTest.java, connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java, connector-server/src/test/resources/application-test.yml
Fixes tests that were not running when #408 was committed (due to accidental Junit4 exclude)
=> Start running test in the sever module

connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/StaticRoutesController.java, connector-server/src/main/resources/application-dev.yml
* Enable JSON MediaType by default for Static Routes
* Add routing-secret for `-dev` profile.
=> Fixes #403

connector-fxrates/src/main/java/org/interledger/connector/fxrates/FxRateOverride.java, connector-persistence/src/main/java/org/interledger/connector/persistence/entities/AccountSettingsEntity.java, connector-persistence/src/main/java/org/interledger/connector/persistence/entities/FxRateOverrideEntity.java, connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/AccountSettingsRepository.java, connector-persistence/src/main/resources/db/changelogs/base/changelog.xml, connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/AccountSettingsRepositoryTest.java, connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/StaticRoutesSpringBootTest.java
Signed-off-by: Ian Simpson <ian.g.simpson@gmail.com>
=> rename natural ids #426

connector-persistence/src/main/java/org/interledger/connector/persistence/entities/DataConstants.java, connector-persistence/src/main/java/org/interledger/connector/persistence/entities/DeletedAccountSettingsEntity.java, connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/DeletedAccountSettingsRepository.java, connector-persistence/src/main/resources/db/changelogs/base/changelog.xml, connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/DeletableAccountSettingsRepositoryTest.java, connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/AccountsController.java, connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java, connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java, connector-server/src/test/java/org/interledger/connector/server/client/ConnectorAdminClient.java, connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java, connector-service-api/src/main/java/org/interledger/connector/accounts/AccountManager.java, connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java, connector-service-impl/src/test/java/org/interledger/connector/accounts/DefaultAccountManagerTest.java
Signed-off-by: Ian Simpson <ian.g.simpson@gmail.com>
=> delete accounts part deux #171

README.md
* Add Docker badge.
* Fix Codacy badge.
=> Fixes #261

README.md, connector-it/src/test/java/org/interledger/connector/it/settlement/TwoConnectorXrpSettlementIT.java, connector-routing-api/src/main/java/org/interledger/connector/routing/PaymentRouter.java, connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/AccountsController.java, connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java, connector-server/swagger/README.md, connector-service-impl/src/main/java/org/interledger/connector/balances/RedisBalanceTracker.java, connector-service-impl/src/main/java/org/interledger/connector/config/CaffeineCacheConfig.java, connector-service-impl/src/main/java/org/interledger/connector/links/DefaultLinkManager.java, connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java, connector-service-impl/src/main/java/org/interledger/connector/settlement/DefaultSettlementService.java, pom.xml
=> Fixes for GH relocation

connector-server/pom.xml, connector-server/src/main/java/org/interledger/connector/server/spring/controllers/MetaDataController.java, connector-server/src/main/java/org/interledger/connector/server/spring/controllers/model/ConnectorSettingsResponse.java, connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java, connector-server/src/test/java/org/interledger/connector/server/spring/controllers/AbstractControllerTest.java, connector-server/src/test/java/org/interledger/connector/server/spring/controllers/MetaDataControllerTest.java
=> Add endpoint to get metadata of controller at root url

connector-crypto/src/main/java/org/interledger/crypto/CryptoKey.java, connector-crypto/src/main/java/org/interledger/crypto/CryptoKeys.java, connector-model/src/main/java/org/interledger/connector/settings/ConnectorSettings.java, connector-model/src/test/java/org/interledger/connector/settings/ConnectorSettingsTest.java, connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java, connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorKeyFromPropertyFile.java, connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorKeysFromPropertyFile.java, connector-server/src/test/java/org/interledger/connector/server/spring/settings/ConnectorSettingsFromPropertyFileTest.java, connector-service-impl/src/main/java/org/interledger/connector/crypto/DefaultConnectorEncryptionService.java
=> Rename ConnectorKey and ConnectorKeys to CryptoKey and CryptoKeys

connector-routing-impl/src/main/java/org/interledger/connector/routing/InterledgerAddressPrefixMap.java, connector-routing-impl/src/test/java/org/interledger/connector/routing/InterledgerAddressPrefixMapTest.java
=> don't match prefixes that are longer than the destination address

connector-core/src/main/java/org/interledger/connector/core/ConfigConstants.java, connector-server/src/test/java/org/interledger/connector/server/javamoney/JavaMoneyConfigTest.java, connector-service-impl/src/main/java/org/interledger/connector/config/CaffeineCacheConfig.java
=> Make fxCache configurable. Defaults to 30s

connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProvider.java, connector-server/src/main/java/org/interledger/connector/server/spring/controllers/ProblemExceptionHandling.java
=> Improve error emission on invalid auth token

connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorParentChildIlpOverHttpTopology.java, connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorPeerIlpOverHttpTopology.java, connector-it/src/main/java/org/interledger/connector/it/topologies/settlement/SimulatedXrplSettlementTopology.java, connector-it/src/test/resources/application.yml, connector-model/src/main/java/org/interledger/connector/settings/ConnectorSettings.java, connector-model/src/main/java/org/interledger/connector/settings/EnabledFeatureSettings.java, connector-server/src/main/resources/application-insecure.yml, connector-server/src/main/resources/application.yml, connector-server/src/test/resources/application-connector-unit-test.yml, connector-service-impl/src/main/java/org/interledger/connector/links/DefaultLinkSettingsValidator.java, connector-service-impl/src/main/java/org/interledger/connector/settings/properties/ConnectorSettingsFromPropertyFile.java, connector-service-impl/src/main/java/org/interledger/connector/settings/properties/EnabledFeatureSettingsFromPropertyFile.java, connector-service-impl/src/test/java/org/interledger/connector/links/DefaultLinkSettingsValidatorTest.java, connector-service-impl/src/test/java/org/interledger/connector/settings/properties/ConnectorSettingsFromPropertyFileTest.java, connector-service-impl/src/test/resources/application-connector-unit-test.yml
=> Move require32ByteSharedSecrets to EnabledFeatureSettings

connector-service-api/pom.xml
=> Fix dependencies

connector-crypto/connector-crypto-cli/pom.xml, connector-crypto/connector-crypto-cli/src/main/java/org/interledger/connector/crypto/cli/shell/commands/EncryptionCommands.java
add sensible defaults for keyringId and keyId
gracefully handle loading and messaging around GOOGLE_APPLICATION_CREDENTIALS
=> package crypto-cli as a docker image

.circleci/config.yml
=> Add dockerhub publishing again

pom.xml
=> Update Quilt to v1.1.1

connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
=> Add more details for Sentry

pom.xml
=> Update Quilt to latest v1.2.0

connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
=> Enable CSP

connector-server/pom.xml, connector-server/src/main/resources/logback-spring.xml, pom.xml
Signed-off-by: nhartner <nhartner@gmail.com>
=> logback appender for logstash format

pom.xml
Signed-off-by: nhartner <nhartner@gmail.com>
=> use quilt 1.3.0
